import React, { useState } from 'react';
import { X, Download, Copy, Check, Award, BarChart3, FileText, Eye, Code, FileSpreadsheet, Printer } from 'lucide-react';
import Markdown from 'react-markdown';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { PlayerReport, ChessGame } from '../types';

interface PlayerReportModalProps {
  report: PlayerReport | null;
  onClose: () => void;
}

export function generateMarkdownReport(report: PlayerReport): string {
  return `# Chess Player Intelligence Report: ${report.username}

**Generated At:** ${new Date(report.generatedAt).toLocaleString()}  
**Total Games Analyzed:** ${report.totalGamesAnalyzed}  
**Overall Win Rate:** ${report.winRate}% (${report.wins} Wins, ${report.losses} Losses, ${report.draws} Draws)  
**Average Opponent Rating:** ${report.avgRating}  
**Highest Opponent Faced/Defeated:** ${report.highestOpponentRating || 'N/A'}  

---

## 1. Key Factual Findings

${report.factualSummaryPoints.map((pt) => `- ${pt}`).join('\n')}

---

## 2. Opening Performance Breakdown

| Opening Name | ECO | Games Played | Win Rate | Wins | Losses | Draws |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${report.openingStats
  .slice(0, 10)
  .map(
    (o) =>
      `| ${o.name} | ${o.eco} | ${o.gamesCount} | ${o.winRate}% | ${o.wins} | ${o.losses} | ${o.draws} |`
  )
  .join('\n')}

---

## 3. Engine Tactical Analysis Summary

- **Brilliant Candidate Games (✦):** ${report.brilliantGamesCount}
- **Blunder Review Games (⚠):** ${report.blunderGamesCount}
- **Average Game Length:** ${report.avgGameLength} moves
- **Recent Form (Last 10):** ${report.recentForm.join(' - ')}

---
*Report generated by Chess Profile Intelligence Platform using official Chess.com PubAPI data.*
`;
}

export function generateGameMarkdown(game: ChessGame): string {
  const whiteResult = game.white.result === 'win' ? '1' : game.white.result === 'draw' ? '½' : '0';
  const blackResult = game.black.result === 'win' ? '1' : game.black.result === 'draw' ? '½' : '0';

  const criticalMoments = game.analysis?.criticalMoments || [];
  const brilliantCount = game.analysis?.brilliantMovesCount || 0;
  const greatCount = game.analysis?.greatMovesCount || 0;

  return `# Game Analysis: ${game.white.username} vs ${game.black.username}

**Result:** ${whiteResult} - ${blackResult}  
**Time Control:** ${game.timeClass.toUpperCase()} (${game.timeControl})  
**Opening:** ${game.openingName || game.eco || 'Standard Chess'} (ECO: ${game.eco || 'N/A'})  
**Estimated Engine Accuracy:** ${game.analysis?.accuracyEstimate ? `${game.analysis.accuracyEstimate}%` : 'N/A'}  
**Tactical Summary:** ${brilliantCount} Brilliant Moves (✦) • ${greatCount} Great Moves (⭐)  

---

## Key Engine Moments & Tactical Highlights

${
  criticalMoments.length > 0
    ? criticalMoments
        .map(
          (cm) =>
            `- **Move ${cm.moveNumber} (${cm.san}):** ${cm.title} - ${cm.description} *(Eval: ${cm.evalBefore} → ${cm.evalAfter})*`
        )
        .join('\n')
    : '- Standard positional flow verified by engine analysis.'
}

---

## Full PGN Game Record

\`\`\`pgn
${game.pgn}
\`\`\`
`;
}

export const PlayerReportModal: React.FC<PlayerReportModalProps> = ({ report, onClose }) => {
  const [copied, setCopied] = useState(false);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [viewMode, setViewMode] = useState<'formatted' | 'markdown_code'>('formatted');

  if (!report) return null;

  const markdownText = generateMarkdownReport(report);

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `chess-report-${report.username}.md`;
    a.click();
  };

  const handleDownloadPdf = async () => {
    setIsExportingPdf(true);
    try {
      const element = document.getElementById('report-pdf-container');
      if (!element) return;

      const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#020617' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210;
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`chess-intelligence-report-${report.username}.pdf`);
    } catch (err) {
      console.error('Failed to export PDF:', err);
    } finally {
      setIsExportingPdf(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/90 backdrop-blur-xl flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden my-auto">
        {/* Header */}
        <div className="p-6 bg-slate-950 border-b border-slate-800 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-amber-500/10 border border-amber-500/30 text-amber-400 rounded-xl">
              <Award className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-xl font-extrabold text-slate-100">
                Player Intelligence Report: @{report.username}
              </h3>
              <p className="text-xs text-slate-400 font-mono">
                Factual statistical analysis derived from public API games
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* View Mode Toggle */}
            <div className="flex items-center bg-slate-900 p-1 rounded-xl border border-slate-800 text-xs font-mono mr-2">
              <button
                onClick={() => setViewMode('formatted')}
                className={`px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-all ${
                  viewMode === 'formatted'
                    ? 'bg-amber-500 text-slate-950 font-bold'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Eye className="w-3.5 h-3.5" />
                Formatted
              </button>
              <button
                onClick={() => setViewMode('markdown_code')}
                className={`px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-all ${
                  viewMode === 'markdown_code'
                    ? 'bg-amber-500 text-slate-950 font-bold'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Code className="w-3.5 h-3.5" />
                Raw Markdown
              </button>
            </div>

            <button
              onClick={handleCopyMarkdown}
              className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl border border-slate-700 flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied' : 'Copy Code'}
            </button>

            <button
              onClick={handleDownloadPdf}
              disabled={isExportingPdf}
              className="px-3.5 py-2 bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-400 hover:to-emerald-500 text-slate-950 text-xs font-extrabold rounded-xl flex items-center gap-1.5 transition-colors shadow disabled:opacity-50"
            >
              <Printer className="w-4 h-4" />
              {isExportingPdf ? 'Generating PDF...' : 'Download PDF'}
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="px-3.5 py-2 bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-bold rounded-xl flex items-center gap-1.5 transition-colors shadow"
            >
              <Download className="w-4 h-4" />
              Export .md
            </button>

            <button
              onClick={onClose}
              className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-colors border border-slate-700"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Content Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-slate-200 font-sans">
          {viewMode === 'formatted' ? (
            <div id="report-pdf-container" className="markdown-body space-y-4 text-slate-200">
              <div className="bg-slate-950 p-6 rounded-2xl border border-slate-800 space-y-4">
                <Markdown
                  components={{
                    h1: ({ children }) => <h1 className="text-2xl font-extrabold text-amber-400 border-b border-slate-800 pb-2 mb-4">{children}</h1>,
                    h2: ({ children }) => <h2 className="text-lg font-bold text-slate-100 mt-6 mb-3 border-b border-slate-800/80 pb-1">{children}</h2>,
                    p: ({ children }) => <p className="text-xs text-slate-300 leading-relaxed my-2">{children}</p>,
                    ul: ({ children }) => <ul className="list-disc list-inside space-y-1 text-xs text-slate-300 my-2">{children}</ul>,
                    li: ({ children }) => <li className="text-xs text-slate-300">{children}</li>,
                    hr: () => <hr className="border-slate-800 my-4" />,
                    table: ({ children }) => (
                      <div className="overflow-x-auto my-4">
                        <table className="w-full text-left text-xs font-mono border-collapse border border-slate-800">{children}</table>
                      </div>
                    ),
                    thead: ({ children }) => <thead className="bg-slate-900 border-b border-slate-800 text-amber-400">{children}</thead>,
                    tbody: ({ children }) => <tbody className="divide-y divide-slate-800/60 text-slate-300">{children}</tbody>,
                    tr: ({ children }) => <tr className="hover:bg-slate-900/50">{children}</tr>,
                    th: ({ children }) => <th className="p-2.5 font-bold border-r border-slate-800">{children}</th>,
                    td: ({ children }) => <td className="p-2.5 border-r border-slate-800">{children}</td>,
                  }}
                >
                  {markdownText}
                </Markdown>
              </div>
            </div>
          ) : (
            <div className="bg-slate-950 p-6 rounded-2xl border border-slate-800">
              <pre className="font-mono text-xs text-emerald-400 overflow-x-auto whitespace-pre-wrap leading-relaxed select-all">
                {markdownText}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
